### ISSUE TITLE
VS 2015 Update 2

### ISSUE THREAD

**Issue by lbargaoanu** [agileobjects/ReadableExpressions#1]
Was this tested with the latest VS 2015? Because I see a NullReferenceException.

**Comment by SteveWilkes** [comment]
Yes, it was. Do you get the exception during install or during use? If the latter, could you add the expression which causes it?

**Comment by lbargaoanu** [comment]
[Expression](https://gist.github.com/lbargaoanu/5361c6a041cb7c0c035121d8f9a5a065) and [stack trace](https://gist.github.com/lbargaoanu/03d7273928070c2400920f702b6afb8d).

**Comment by SteveWilkes** [comment]
Apparently Expression.Rethrow creates a UnaryExpression with a null Operand - I've fixed the translation of this in v1.1.2, which I've uploaded.

**Comment by lbargaoanu** [comment]
Thanks.
