### ISSUE TITLE
How to see resolved expression from debugger in VS 2017?

### ISSUE THREAD

**Issue by ggirard07** [agileobjects/ReadableExpressions#10]
Following up comment on [blog post here](http://geekswithblogs.net/mrsteve/archive/2016/04/05/readable-expression-tree-debugger-visualizers-visual-studio-gallery.aspx).
### Reproduction Step ###
1. Create a dummy project with AutoMapper
2. Add a few mapping to AutoMapper config like
```csharp
AutoMapper.Mapper.Initialize(cfg =>
{
    cfg.AllowNullCollections = true;
    cfg.CreateMap<Entity1, Entity1VM>().ReverseMap();
    cfg.CreateMap<Entity2, Entity2VM>().ReverseMap();
});

var expression = AutoMapper.Mapper.Configuration.BuildExecutionPlan(typeof(Entity1), typeof(Entity1VM));
```
3. In debug, break right after `expression` has been initialized.
4. Add expression to Watch window.

### Expected behavior ### 
Don't really know where to see the resolved expression. Should it be displayed from the Watch window?

### Actual result ###
Here is what I currently get in Watch window.
![image](https://cloud.githubusercontent.com/assets/2625886/26220553/1333dea2-3be1-11e7-80b2-db980492d6e1.png)

### Information ###
Regarding your question from the blog post, the `AgileObjects.ReadableExpressions.Visualizers.Vs15.dll` assembly is properly located in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Packages\Debugger\Visualizers`.

### Versions ###
Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.6) Release
VisualStudio.15.Release/15.2.0+26430.6
Microsoft .NET Framework
Version 4.6.01586

ReadableExpressions.Visualizers v1.8.6

**Comment by SteveWilkes** [comment]
Thanks for the info! The expression visualizer should be accessible through a magnifying glass icon either next to any tooltip which pops up when you mouse over an expression, or all the way to to the right of the Value column in the Watch window.

If the magnifying icons are missing, could you confirm - in VS, if you go to Tools > Extensions and Updates, is ReadableExpressions.Visualizers listed?

**Comment by SteveWilkes** [comment]
...also do you have any other versions of VS installed?

**Comment by ggirard07** [comment]
Thanks for the information! Is is actually working probably, I just did not know how to use it :)
My only mistake was to try to use it from inside the expression object in the Watch window, and not on the whole object...
![expression](https://cloud.githubusercontent.com/assets/2625886/26250664/c394ba7c-3c78-11e7-9fa5-512035d15b8f.gif)

Sorry for the inconvenience and thanks for this really great tool for those like me who knows nothing about expressions!

**Comment by SteveWilkes** [comment]
Ahhh, glad it's working :) Enjoy!
