### ISSUE TITLE
Extending Expression visualization without any additional references to `ReadableExpressions` library.

### ISSUE THREAD

**Issue by sdanyliv** [agileobjects/ReadableExpressions#115]
Hi @SteveWilkes, it is just idea and probably you will propose better solution.

For example, we have custom expression:
```cs
public class MyExpression : Expression
{
    public MyExpression(IReadOnlyList<(MemberInfo, Expression)> assignments)
    {
        Assignments = assignments;
    }

    public IReadOnlyList<(MemberInfo member, Expression expression)> Assignments { get; }

    public override bool           CanReduce => false;
    public override ExpressionType NodeType => ExpressionType.Extension;
    public override Type           Type     => typeof(object);

    /// <summary>
    /// Just idea if method signature. ReadableExpressions visualizer just search for such method with this signature.
    /// </summary>
    /// <param name="sb">Output StringBuilder.</param>
    /// <param name="indent">Current indentation.</param>
    /// <param name="formatter">ReadableExpressions formatter delegate.</param>
    public void ToReadableExpression(StringBuilder sb, int indent, Action<Expression, StringBuilder, int> formatter)
    {
        sb
            .Append('\t', indent).AppendLine("new")
            .Append('\t', indent).AppendLine("{");

        ++indent;
        foreach (var member in Assignments)
        {
            sb.Append('\t', indent)
                .Append(member.member)
                .Append(" = ");

            // visualize expression via callback
            formatter(member.expression, sb, indent);
        }
        --indent;

        sb
            .AppendLine()
            .Append('\t', indent).AppendLine("}");
    }
}
```
In this case we can visualize our expressions without any additional dependencies. Currently similar code is put into `ToString()` but for sure it looks ugly at he end.

How do you think, It is possible and makes sense? I saw `ITranslation` in documentation, but it's additional dependencies and probably we have to make conditional build for our library to do not create dependency in release configuration. Also our Expressions all have `ExpressionType.Extension`

**Comment by SteveWilkes** [comment]
Hello!

We could _probably_ support this by duck-typing something like this:

```cs
void Translate(dynamic writer);
```

...where the passed object would be a [`TranslationWriter`](https://github.com/agileobjects/ReadableExpressions/blob/2dc0e4b57efd7ee4c6eccc6bb647d8c506ad7365/ReadableExpressions/Translations/TranslationWriter.cs). That would be a non-trivial change though, so maybe adding ReadableExpressions as a development dependency, adding a debug-only `READABLE` compile-time constant and implementing [`ICustomTranslationExpression`](https://github.com/agileobjects/ReadableExpressions/blob/2dc0e4b57efd7ee4c6eccc6bb647d8c506ad7365/ReadableExpressions/Translations/ICustomTranslationExpression.cs) with `#if READABLE` pragmas would get you there more quickly?

**Comment by sdanyliv** [comment]
Let me play with this a little bit. Will try conditional compilation...
