### ISSUE TITLE
Concatenation Visualization

### ISSUE THREAD

**Issue by gaborbalazs** [agileobjects/ReadableExpressions#116]
Greetings, I would like to point out a misleading visualization:

The expression
`Concat(new[] { Convert(1, Object), Convert((1 + 1), Object), Convert(3, Object) })`
appears as
`1d + (1d + 1d) + 3d`,
which is not resulting to 6 but "123"

**Comment by SteveWilkes** [comment]
Thanks for the bug report - this will be fixed in the next release :)

**Comment by SteveWilkes** [comment]
This is fixed as of v4.1 of the package, which is now [on NuGet](https://www.nuget.org/packages/AgileObjects.ReadableExpressions/4.1.0) - visualizers release to follow. Cheers!
