### ISSUE TITLE
Guid constant

### ISSUE THREAD

**Issue by lbargaoanu** [agileobjects/ReadableExpressions#119]
var guid = Guid.NewGuid();
	var lambda = Expression.Lambda(Expression.Constant(guid));
	lambda.ToReadableString().Dump();
I get smth like `() => e157dc9e-2e1d-4cfa-8d96-543f84c21fc5`.  Perhaps most efficient would be to leverage https://github.com/dotnet/roslyn/pull/24621. But `new Guid(string)` is certainly more readable :)

**Comment by SteveWilkes** [comment]
Thanks for the report - this will be fixed in the next release :)

**Comment by lbargaoanu** [comment]
Thanks!

**Comment by SteveWilkes** [comment]
This is fixed as of v4.1 of the package, which is now [on NuGet](https://www.nuget.org/packages/AgileObjects.ReadableExpressions/4.1.0). Cheers!

**Comment by lbargaoanu** [comment]
Thanks for solving _all_ these issues :)

**Comment by SteveWilkes** [comment]
> Thanks for solving _all_ these issues :)

You're welcome! Takes a bit longer these days, but I get there in the end :)
