### ISSUE TITLE
Dictionary get missing parentheses

### ISSUE THREAD

**Issue by lbargaoanu** [agileobjects/ReadableExpressions#122]
Expression<Func<object, string>> expr = o => ((Dictionary<string, string>)o)["key"];
	expr.ToReadableString().Dump();

I get `o => (Dictionary<string, string>)o["key"]`.

**Comment by SteveWilkes** [comment]
Thanks for the bug report - this will be fixed in the next release :)

**Comment by SteveWilkes** [comment]
This is fixed as of v4.1 of the package, which is now [on NuGet](https://www.nuget.org/packages/AgileObjects.ReadableExpressions/4.1.0). Cheers!
