### ISSUE TITLE
Missing ToString with Concat

### ISSUE THREAD

**Issue by lbargaoanu** [agileobjects/ReadableExpressions#123]
Expression<Func<object, int, string>> expr = (obj, integer)=>obj.ToString()+integer.ToString();
	expr.ToReadableString().Dump();

I get `(obj, integer) => obj + integer`, but that's not valid C#.

**Comment by SteveWilkes** [comment]
Thanks for the report - this will be fixed in the next release :)

**Comment by SteveWilkes** [comment]
This is fixed as of v4.1 of the package, which is now [on NuGet](https://www.nuget.org/packages/AgileObjects.ReadableExpressions/4.1.0). Cheers!
