### ISSUE TITLE
Correct parantheses for arithmetic unary minus

### ISSUE THREAD

**Issue by Zerseu** [agileobjects/ReadableExpressions#13]
Please correct me if I'm wrong, but shouldn't double negation of x yield "-(-x)"?
Instead it returns "--x".

The following statement fails:
Assert.AreEqual(Expression.Negate(Expression.Negate(Expression.Parameter(typeof(double), "x"))).ToReadableString(), "-(-x)");

**Comment by SteveWilkes** [comment]
Hi!

The two look to produce the same result (see [this fiddle](https://dotnetfiddle.net/qOlGuy)) so I think it's just a question of coding style. The library generally minimises use of parentheses.

Thanks for the feedback :)
