### ISSUE TITLE
Extension: "An unhandled exception of type 'System.ArgumentException' was thrown by the custom visualizer component in the process being debugged" when clicking "View" on a Func (not Expression)

### ISSUE THREAD

**Issue by IanKemp** [agileobjects/ReadableExpressions#137]
Extension version: 4.6.0 (latest as at time of writing)
Visual Studio version: 2022 Professional 17.9.2 (latest as at time of writing)

![image](https://github.com/agileobjects/ReadableExpressions/assets/1726434/ba774b52-9752-4156-8821-e5008595c177)

The following is also logged in the Output window:

```
System.MissingMethodException thrown when loading the VisualizerAssemblyLoadContext. Message: Cannot dynamically create an instance of type 'Microsoft.VisualStudio.NetCoreAssemblyResolution.VisualizerAssemblyLoadContext'. Reason: No parameterless constructor defined.
```

**Comment by Giorgi** [comment]
Related: [System.MissingMethodException thrown when opening the EFCore.Visualizer extension in Visual Studio 2022 version 17.9.2](https://developercommunity.visualstudio.com/t/SystemMissingMethodException-thrown-whe/10612094)

**Comment by SteveWilkes** [comment]
Thanks for the bug report - I'm going to close as as per @Giorgi 's link, this doesn't appear to be an issue with the visualizers themselves.
