### ISSUE TITLE
Extension suggestion: add Close button to make UI more consistent with QuickWatch

### ISSUE THREAD

**Issue by IanKemp** [agileobjects/ReadableExpressions#138]
![image](https://github.com/agileobjects/ReadableExpressions/assets/1726434/489a24cf-d156-4fd9-8724-3febd866b82a)

As you can see from the above, the QuickWatch window has a "Close" button at the bottom-right. Muscle memory means I assume that the "Copy" button in the ReadableExpressions visualisation window is also a close button, and when I click it I get confused because the window doesn't close.

I would suggest adding an actual Close button to the right of the Copy button.

**Comment by SteveWilkes** [comment]
Thanks for the suggestion - sounds reasonable! Will do :)

**Comment by SteveWilkes** [comment]
The close button has been added in release 4.7. Cheers!
