### ISSUE TITLE
Failed to uninstall: Microsoft.VisualStudio.ExtensionManager.InstallByMsiException

### ISSUE THREAD

**Issue by Phoenixkaze** [agileobjects/ReadableExpressions#144]
I wanted to uninstall it via Extension Manager but it failed. VS 2022 WIndows 11

The logs say Microsoft.VisualStudio.ExtensionManager.InstallByMsiException was thrown and I must uninstall it in Programs and Features in Control Panel.

But I can't find it in Programs and Features nor uninstall via the context menu of the msi installer.

**Comment by SteveWilkes** [comment]
It should be listed in Add / Remove Programs, e.g:
![image](https://github.com/agileobjects/ReadableExpressions/assets/8459425/da93f529-3ab9-47aa-8b10-434ee88acdcf)

**Comment by Phoenixkaze** [comment]
Weird. I also checked that. But it's not there.

**Comment by SteveWilkes** [comment]
That is weird!

You can manually remove it by deleting:
- \Program Files\Microsoft Visual Studio\2022\[Version]\Common7\IDE\Extensions\AgileObjects
- \Program Files\Microsoft Visual Studio\2022\[Version]\Common7\Packages\Debugger\Visualizers\**\AgileObjects.*.dll
