### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ewgoforth** [agileobjects/ReadableExpressions#145]
I got this error code when running the Expression Trees in C# demo code from Pluralsight.  

The author of the course was demonstrating the ReadableExpressions.  According to the screenshot he is using v4.4.0

Here's a link to the repo he was using:

https://github.com/FeynmanFan/csharp-expression-trees.git

I was trying to use the extension to view the following expression:

    public class UnitTest1
    {
        [Fact]
        public void IsPrime()
        {
            var value = Expression.Parameter(typeof(int), "value");

            var result = ScriptingEngine.IsPrime(value);

            var expr = Expression.Lambda<Func<int, bool>>(result, value);

**Comment by SteveWilkes** [comment]
Hi,

Thanks for letting me know about this - from my own testing it appears whatever the issue was is now fixed. I can successfully translate the built Expression using both `ToReadableString()`:

```cs
value =>
{
    bool result;

    if (value <= 1)
    {
        return false;
    }

    if (value == 2)
    {
        return true;
    }

    if ((value % 2) == 0)
    {
        return false;
    }

    var i = 3;
    var boundary = (int)Math.Floor(Math.Sqrt((double)value));
    while (true)
    {
        if (i <= boundary)
        {
            if ((value % i) == 0)
            {
                return false;
            }

            i += 2;
        }
        else
        {
            break;
        }
    }

    return true;
}
```

..and the visualizer:

![image](https://github.com/user-attachments/assets/49148c24-1aa7-4aef-9400-89a7ad868e0d)
