### ISSUE TITLE
VS 2017 - Magnifying glass icon duplicated

### ISSUE THREAD

**Issue by rizi** [agileobjects/ReadableExpressions#16]
Hi, I'm using VS 2017 Enterprise (15.6.4), when hovering over a lambda expression two magnifying glasses are shown (see the picture attached), no matter on which one I click it shows me the same result.
Is this a bug or do I miss something?
Thx in advance

![readableexpressions visualizers](https://user-images.githubusercontent.com/796258/38288109-d4e7008a-37ce-11e8-82be-66fcb5e75bf2.png)

**Comment by SteveWilkes** [comment]
Hi!

Does the project target multiple versions of the .NET Framework? That's the only circumstances where I've seen something similar to this (but not this).

In any event, this is down to how Visual Studio is rendering the visualizer options, so is a Visual Studio bug if anything.

Thanks for the feedback!

Steve
