### ISSUE TITLE
Installer opens and the immediately closes

### ISSUE THREAD

**Issue by VictorioBerra** [agileobjects/ReadableExpressions#17]
This is what I get and then the window disappears 
![image](https://user-images.githubusercontent.com/2934507/40495669-6e154f9c-5f3d-11e8-9245-4de15e6db1e2.png)

![image](https://user-images.githubusercontent.com/2934507/40495710-8ad929f0-5f3d-11e8-9367-d8aa3cca3d8b.png)

A system reboot had no effect.

**Comment by VictorioBerra** [comment]
MSI Logs:

```
=== Logging stopped: 5/24/2018  10:37:05 ===
MSI (c) (58:28) [10:37:05:753]: Note: 1: 1728 
MSI (c) (58:28) [10:37:05:753]: Note: 1: 2205 2:  3: Error 
MSI (c) (58:28) [10:37:05:753]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1728 
MSI (c) (58:28) [10:37:05:753]: Note: 1: 2205 2:  3: Error 
MSI (c) (58:28) [10:37:05:753]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (c) (58:28) [10:37:05:753]: Product: AgileObjects.ReadableExpressions.Visualizers -- Configuration completed successfully.

MSI (c) (58:28) [10:37:05:754]: Windows Installer reconfigured the product. Product Name: AgileObjects.ReadableExpressions.Visualizers. Product Version: 1.11.0.0. Product Language: 1033. Manufacturer: AgileObjects. Reconfiguration success or error status: 0.

MSI (c) (58:28) [10:37:05:755]: Grabbed execution mutex.
MSI (c) (58:28) [10:37:05:755]: Cleaning up uninstalled install packages, if any exist
MSI (c) (58:28) [10:37:05:756]: MainEngineThread is returning 0
=== Verbose logging stopped: 5/24/2018  10:37:05 ===
```

**Comment by SteveWilkes** [comment]
Hi!

Thanks for the feedback! I would guess that the installer is failing to find any installed copies of Visual Studio - out of interest, which version do you have installed? - but unfortunately custom debugger visualizers don't work with .NET Core, no.

You can still get readable versions of Expressions using [the NuGet package](https://www.nuget.org/packages/AgileObjects.ReadableExpressions) - it's a bit more long winded:

```C#
var expression = GetAnExpression();

// View the value of `readable` in a watch or using the built-in string visualizer:
var readable = expression.ToReadableString();
```

...but it'll work in .NET Core.

I'd like to support Core, but unfortunately Microsoft's visualizer base classes don't! The [User Voice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33344638-custom-debugger-visualizer-for-net-core-apps-in-v) is to get Microsoft to support it :)

Steve

**Comment by VictorioBerra** [comment]
Thanks a lot for the code snippet. Hopefully they improve extensibility.
