### ISSUE TITLE
MSI Installer Issues

### ISSUE THREAD

**Issue by InteXX** [agileobjects/ReadableExpressions#19]
I previously reported this in the [MarketPlace Q&A](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers#qna), but I think I've figured out what might be happening.

I'm encountering the same behavior as reported [here](https://github.com/agileobjects/ReadableExpressions/issues/17); however, I'm not using .NET Core. I'm using .NET Framework v4.7.1.

Based on the attached log, it seems that installation succeeded. It appears I've been laboring under the mistaken impression that it didn't, because the installer didn't pause to indicate success. Most MSIs do—in fact, this is the first one I've encountered in all these years that doesn't.

I do now have the assembly `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Packages\Debugger\Visualizers\AgileObjects.ReadableExpressions.Visualizers.Vs15.dll"` as indicated. I haven't tried to use it yet, as I don't have any code handy for which I need it (I'm trying this out for potential future use).

Anyway... with this now it seems all is well.

Can you confirm that my experience aligns with the expected behavior of the MSI?

---
[MSI6dec4.LOG](https://github.com/agileobjects/ReadableExpressions/files/2281404/MSI6dec4.LOG)

**Comment by InteXX** [comment]
In addition, I now have this in Visual Studio's Tools & Extensions dialog:

![Dialog](https://user-images.githubusercontent.com/10966749/44007778-c78c005e-9e47-11e8-92bb-fc8235d94285.png)

**Comment by SteveWilkes** [comment]
Hi,

That is what the MSI does, yeah - you're absolutely right that it should provide feedback on the installation, and I'll think I'll add that in a future release.

Cheers,

Steve

**Comment by InteXX** [comment]
@SteveWilkes 

Sounds good, thanks.

Oh, and I remembered an MSI from some years ago that didn't pause. I don't remember what it was for, but I figured I'd let you off the hook at least.

Thank you for all that you do.

**Comment by SteveWilkes** [comment]
Just to mention, [the v1.13 installer](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers) now has a basic UI and reports which versions of VS it's found and installed extensions for.

Cheers! :)

**Comment by InteXX** [comment]
@SteveWilkes 

Excellent, thank you.
