### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by lbargaoanu** [agileobjects/ReadableExpressions#2]
[Expression and stack trace.](https://gist.github.com/lbargaoanu/08f0d4413d86cec2590b8a57bf4be9c2#file-expressionvisualizernre)

**Comment by SteveWilkes** [comment]
The exception is being thrown translating the catch block in here:
```
    $dest.Value = (System.String).If (.Try {
                        (System.String).Invoke (...)
                    } .Catch (System.Exception) {
                        .Default(System.String)
                    } == .Default(System.String)) {
                        null
                    }
```
...but I'm unable to reproduce it, and already have a passing test which does something very similar - ShouldAssignTheResultOfATryCatch in [WhenTranslatingAssignments](https://github.com/agileobjects/ReadableExpressions/blob/8ebf86f35c4d631b88199288622b72458ceaab72/ReadableExpressions.UnitTests/WhenTranslatingAssignments.cs).

Are you using the latest version?
Is the code which produces the exception on a branch I can download and run?

**Comment by lbargaoanu** [comment]
I'm using the version that fixed #1. That code is from the latest AutoMapper. It seems difficult for you to try that out :) I'll try to make a repro somehow.

**Comment by SteveWilkes** [comment]
The issue you're seeing was fixed [in v1.2](https://github.com/agileobjects/ReadableExpressions/commit/3bba17044a49ddba691c15d0c55d8b84c7fe90a8). Upgrading will fix it, but it seems difficult for you to try that out :)

**Comment by lbargaoanu** [comment]
I guess I should have upgraded first, but I didn't even consider it, I probably thought the extension would update itself. I wasn't being sarcastic or anything. I just thought it would be difficult for you to set a breakpoint in some random code in AutoMapper. That's what I was doing at the time. Thanks.

**Comment by SteveWilkes** [comment]
No worries! It's not an auto-updater unfortunately because it has to use an MSI. Glad you're finding it useful, though! :)

**Comment by lbargaoanu** [comment]
Looks good with the latest version. A few other smaller issues :) The window needs scrolling (I needed the vertical one, but both I suppose). The extension version number in VS does not appear to be updated. I think it might be possible to notify of existing updates (not actually installing them).

**Comment by SteveWilkes** [comment]
Thanks for the feedback! The scrolling's a funny one - it does scroll vertically but not horizontally so if the translated expression is 'wide' it pushes the vertical scrollbar beyond the right-hand side of the window. I'll raise a bug for it and look at sorting it out today.

I'll check the version numbers too - that should be working as far as I know...

**Comment by SteveWilkes** [comment]
Scrolling bug #3 fixed in version 1.4.2. VS not automatically notifying of new versions - raised by #4.

**Comment by lbargaoanu** [comment]
Cool :+1:

**Comment by lbargaoanu** [comment]
I've done a little research. Not much to show for :) The version number was not updated because I didn't uninstall older versions, I just installed the new ones. About the update notification, I see that VS is inquiring about the extension using its id (2d5de770-50e9-4dcf-87e9-ea1ed1b43b68), but it gets nothing in return. It does get latest version values for other extensions. So I guess [the server] (https://visualstudiogallery.msdn.microsoft.com/Services/VStudio/Extension.svc) doesn't know the latest version, it must be told somehow, some kind of registration. That's all I got.

**Comment by SteveWilkes** [comment]
Cool, thanks very much for looking into it :) I'll be checking it out again today...

**Comment by lbargaoanu** [comment]
Another idea is to integrate [some code](http://blogs.msdn.com/haibo_luo/archive/2010/04/19/9998595.aspx) to show the IL generated for the expression. People who use expressions do it often for performance and sometimes is useful see the generated IL.

**Comment by SteveWilkes** [comment]
Nice idea - I'll check it out :)
Still no luck with the upgrade bug...
