### ISSUE TITLE
Unnamed variable should use generated name

### ISSUE THREAD

**Issue by MaceWindu** [agileobjects/ReadableExpressions#21]
Expression:
```
.Lambda #Lambda1<System.Action`2[System.Object,System.Object]>(
    System.Object $obj,
    System.Object $value) {
    .Block(System.Int32 $var1) {
        $var1 = 0
    }
}
```
Expected:
```cs
// generate unique name for variable, e.g. $varN
(obj, value) => var $var1 = 0
```
Actual:
```cs
(obj, value) => var  = 0
```

**Comment by SteveWilkes** [comment]
Fixed in the latest code - release to follow. Thanks! :)

**Comment by SteveWilkes** [comment]
Added in v1.13, which is [on NuGet](https://www.nuget.org/packages/AgileObjects.ReadableExpressions) and in [the Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers).

Thanks for the feedback! :)
