### ISSUE TITLE
MSI does not install for VS2017 Enterprise

### ISSUE THREAD

**Issue by StanleyGoldman** [agileobjects/ReadableExpressions#24]
👋 Hello,

Testing out your debugger visualizer, and I notice it does not install for Visual Studio 2017 Enterprise.

I have 2015 Professional and 2017 Enterprise installed.
The extension appears in the 2015 list and not in the 2017 list.

```
=== Logging stopped: 9/19/2018  10:54:51 ===
MSI (c) (5C:E8) [10:54:51:283]: Note: 1: 1707 
MSI (c) (5C:E8) [10:54:51:283]: Note: 1: 2205 2:  3: Error 
MSI (c) (5C:E8) [10:54:51:283]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1707 
MSI (c) (5C:E8) [10:54:51:283]: Note: 1: 2205 2:  3: Error 
MSI (c) (5C:E8) [10:54:51:283]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (c) (5C:E8) [10:54:51:283]: Product: AgileObjects.ReadableExpressions.Visualizers -- Installation completed successfully.

MSI (c) (5C:E8) [10:54:51:284]: Windows Installer installed the product. Product Name: AgileObjects.ReadableExpressions.Visualizers. Product Version: 1.12.1.0. Product Language: 1033. Manufacturer: AgileObjects. Installation success or error status: 0.

MSI (c) (5C:E8) [10:54:51:284]: Grabbed execution mutex.
MSI (c) (5C:E8) [10:54:51:284]: Cleaning up uninstalled install packages, if any exist
MSI (c) (5C:E8) [10:54:51:285]: MainEngineThread is returning 0
=== Verbose logging stopped: 9/19/2018  10:54:51 ===
```

**Comment by StanleyGoldman** [comment]
I'm trying to follow with where this is breaking down for me, but I'm unfamiliar with programming wix installers.

https://github.com/agileobjects/ReadableExpressions/blob/80bb593360cdee7f8f67400eb3f3e3f699693847/ReadableExpressions.Visualizers.Installer.Custom/VisualizerInstallationActions.cs#L178-L188

![image](https://user-images.githubusercontent.com/417571/45764209-30d3aa00-bc00-11e8-8a3f-aba261783d57.png)

**Comment by StanleyGoldman** [comment]
Hmm, I copied `AgileObjects.ReadableExpressions.Visualizers.Vs15.dll` to `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Packages\Debugger\Visualizers`. I'm getting this exception when attempting to use the visualizer.

![image](https://user-images.githubusercontent.com/417571/45764867-ae4bea00-bc01-11e8-8df0-c6b898de4054.png)

**Comment by SteveWilkes** [comment]
Hey there!

Just to check:

- Are you debugging a full .NET Framework (i.e. non-.NET Core) application?

- The VS registry settings are probably at:

HKEY_LOCAL_MACHINE\SOFTWARE\\**WOW6432Node**\Microsoft

...in **VisualStudio\\[Version numbers]** or **VisualStudio_[some random string]** - do you have those? If so for VS2017+ the installer looks for a **Capabilities** sub key, then tries to get the install path from an **ApplicationDescription** value in there.

- For a manual install, you might also need to copy the extension manifest into:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\AgileObjects\ReadableExpressions.Visualizers\1.12.1

...from the equivalent 2015 folder, and run `devenv.exe /setup` to reset the extensions list - does that help?

Thanks for the feedback!

Steve

**Comment by StanleyGoldman** [comment]
Hey @SteveWilkes 

I'm debugging an application with .NET Core and .NET Framework targets, I'm attempting to see this visualizer debugging a test with the .NET Framework.

I'll check your other points soon.

**Comment by SteveWilkes** [comment]
I've now updated the installer (in the latest code) to report which versions of Visual Studio it finds and installs the visualizers for, and confirmed it install and works on VS 2017 Enterprise.

Release to follow! :)

**Comment by SteveWilkes** [comment]
I've now uploaded a new [NuGet package](https://www.nuget.org/packages/AgileObjects.ReadableExpressions) and [visualizers installer](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers) - please let me know how you get on!

And thanks again for the feedback! :)

**Comment by StanleyGoldman** [comment]
Ah sweet. Sorry I didn't get back to you about this sooner. It was on my list.

**Comment by StanleyGoldman** [comment]
![image](https://user-images.githubusercontent.com/417571/46169239-7e878c80-c268-11e8-9841-cff8a19f7c86.png)

**Comment by StanleyGoldman** [comment]
What should I do to help you debug?

**Comment by StanleyGoldman** [comment]
![image](https://user-images.githubusercontent.com/417571/46173202-a03a4100-c273-11e8-853d-8b43fd6e1c49.png)

![image](https://user-images.githubusercontent.com/417571/46173233-adefc680-c273-11e8-9a25-9c16b2f2f918.png)

**Comment by SteveWilkes** [comment]
Thanks! VS Enterprise should be that `VisualStudio_24c77e3d` key - that has a `Capabilities` subkey, which I'd expect to have values for `ApplicationName` and `ApplicationDescription` - is that right? If so what are those values?

**Comment by StanleyGoldman** [comment]
Ack... you asked for those specifically and I skipped two...

![image](https://user-images.githubusercontent.com/417571/46207376-319dc780-c2f5-11e8-9851-bda9226bddfd.png)

I also exported the keys for your viewing...

[VisualStudio_24c77e3d.reg.txt](https://github.com/agileobjects/ReadableExpressions/files/2428066/VisualStudio_24c77e3d.reg.txt)
[VisualStudio_39bc66df.reg.txt](https://github.com/agileobjects/ReadableExpressions/files/2428067/VisualStudio_39bc66df.reg.txt)
[VisualStudio_abbe6b87.reg.txt](https://github.com/agileobjects/ReadableExpressions/files/2428068/VisualStudio_abbe6b87.reg.txt)

**Comment by StanleyGoldman** [comment]
`abbe6b87` is the only one with data in it

**Comment by SteveWilkes** [comment]
Thanks! I see what the issue is now - the `ApplicationName` having `(Enterprise)` on the end is tripping up the installer as it tries to find the VS version - I'll fix it and get a patch release out.

Thanks again! :)

**Comment by StanleyGoldman** [comment]
Sweet

**Comment by SteveWilkes** [comment]
This is fixed in v1.13.1, the installer for which is currently verifying on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers). Thanks for your help!

**Comment by StanleyGoldman** [comment]
Good to go! 👍 

![image](https://user-images.githubusercontent.com/417571/46350608-27483a00-c623-11e8-997b-6ae3717063c7.png)

**Comment by SteveWilkes** [comment]
Yay! Thanks again for your help :)
