### ISSUE TITLE
Using full Type names when translating i.e. Expression.Default

### ISSUE THREAD

**Issue by kemsky** [agileobjects/ReadableExpressions#27]
Hi, is it possible to force using full type names in `ToReadableString`? Otherwise we need to add `using` sections manually.

**Comment by SteveWilkes** [comment]
Hi!

Thanks for the suggestion - I'll add a configuration option for it :)

Cheers,
Steve

**Comment by SteveWilkes** [comment]
I've added support for this in the latest code:

```C#
var readable = expression.ToReadableString(s => s.UseFullyQualifiedTypeNames);
```

...release to follow. Thanks! :)

**Comment by SteveWilkes** [comment]
This is included in the NuGet package on the [v2 release page](https://github.com/agileobjects/ReadableExpressions/releases/tag/v2.0.0) - I'll be publishing it on NuGet in a few days.

**Comment by kemsky** [comment]
Thanks, Steve!

**Comment by SteveWilkes** [comment]
You're welcome! :)

**Comment by SteveWilkes** [comment]
Just to note, [the v2 package](https://www.nuget.org/packages/AgileObjects.ReadableExpressions) is now up on NuGet! Thanks again for the feedback :)
