### ISSUE TITLE
VS 2019 support

### ISSUE THREAD

**Issue by zihotki** [agileobjects/ReadableExpressions#30]
Opening this issue to track support of the extension for VS 2019 which is currently in Preview 1.

**Comment by SteveWilkes** [comment]
An installer for the [v2.1 pre-release](https://github.com/agileobjects/ReadableExpressions/releases/tag/v2.1.0) is now available on the releases page, and supports VS 2019.

**Comment by zihotki** [comment]
Wow, that was fast, thank you very much for your effort

**Comment by SteveWilkes** [comment]
You're welcome! :)

**Comment by SteveWilkes** [comment]
I've now released v2.1 to [the VS marketplace](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers) :)
