### ISSUE TITLE
KeyNotFoundException from extension

### ISSUE THREAD

**Issue by MaceWindu** [agileobjects/ReadableExpressions#31]
![image](https://user-images.githubusercontent.com/1099238/51827701-48c3e480-22ea-11e9-84ef-b0d3f9c52885.png)

Will see if I can provide more details

**Comment by SteveWilkes** [comment]
Thanks for the info - this was being thrown when a lambda with an unnamed parameter is passed as a method call argument.

Fixed in the latest code, release to follow. Cheers! :)

**Comment by SteveWilkes** [comment]
Fixed in v2.1.1, which is now on NuGet and in the VS Marketplace. Thanks! :)
