### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by fire-birdie** [agileobjects/ReadableExpressions#32]
VS 2019 Preview 1 added [custom visualizer support for .NET Core apps](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#general-debugging), but trying to use ReadableExpressions in one results in the following error:

> Unable to load the custom visualizer.
> 
> **Additional informaiton:**
> The debuggee-side visualizer assembly 'AgileObjects.ReadableExpressions.Visualizers.Vs16, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' was not found at path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\Packages\Debugger\Visualizers\netstandard2.0'.
>
> [Learn more about managed custom visualizers](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vs.debug.visualizer.troubleshoot);k(DevLang-csharp)%26rd%3Dtrue&view=vs-2017)

Copying the assembly to the path mentioned in the error fixes the problem.

**Comment by SteveWilkes** [comment]
Thanks for letting me know! I'll update the installer to fix this.

Cheers,

Steve

**Comment by SteveWilkes** [comment]
This is fixed in [the installer](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers) as of v2.1.2. Thanks again for the feedback! :)
