### ISSUE TITLE
Body of Expression with type Func[SomeClass, AnonymousType] isn't resolved with the custom naming factory 

### ISSUE THREAD

**Issue by arcadiogarcia** [agileobjects/ReadableExpressions#33]
I tried using ReadableExpressions to convert an Expression that contains a Func[SomeClass, AnonymousType] to C# code:

```csharp
expression.Body.ToReadableString(c=>c.NameAnonymousTypesUsing(x=>MyNameFactory(x)))
````

however, it returns

`new {A = x.A, B = x.B}`

which, while it is valid code, drops the type information. I'd expect the anonymous type to be presserved and renamed using the factory I provided (which currently is not being called), returning something like this:

`new MyClassNameAsGeneratedByMyFactory(){A = x.A, B = x.B}`

Is this by design or is it a bug?

**Comment by SteveWilkes** [comment]
This has been fixed in v2.2, which is now [on NuGet](https://www.nuget.org/packages/AgileObjects.ReadableExpressions). Thanks for letting me know!

Cheers,

Steve

**Comment by arcadiogarcia** [comment]
Thanks for the quick turnaround! 😄

**Comment by SteveWilkes** [comment]
You're welcome! :)
