### ISSUE TITLE
Issue with displaying expression with \0 (0x00) character

### ISSUE THREAD

**Issue by MaceWindu** [agileobjects/ReadableExpressions#43]
(This issue affects also visual studio's visualizer)
If visualized expression contains \0 in character/string constant, visualization displays expression only to that point. I suspect that rendered expression doesn't escape it and visual studio window, used for display, treat it as terminating character.

**Comment by SteveWilkes** [comment]
Thanks for letting me know! This is fixed in v2.3.2 of [the NuGet package](https://www.nuget.org/packages/AgileObjects.ReadableExpressions) and v2.4 of [the Visualizers](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers).

**Comment by MaceWindu** [comment]
Cool! That was really annoying issue. Not sure why I was tolerating it for so long :smile:
