### ISSUE TITLE
VS2019 2.4.0 Update issues.

### ISSUE THREAD

**Issue by sdanyliv** [agileobjects/ReadableExpressions#46]
Hi, just tried to update to 2.4.0. Without success.
Uninstalling and then installing again shows that i have installed version 2.3.2  - why?
Manage Extensions window shows that i have update from 2.3.2 to 2.4.0.

Maybe there are some ways to cleanup registry or some folders to force installing correct version?
Visualizing types is not working as expected.

MSI file shows that it was created yesterday. But maybe with old content.

VS Professional 2019, Version 16.1.5

**Comment by SteveWilkes** [comment]
Oh dear, sorry about that - the VS 2019 visualizer wasn't linked properly and the installer had the 2.3.2 assembly in it.

I've just uploaded [2.4.1](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers) with the assembly linking fixed, have tested the installer and it works:

![TypeVisualizers](https://user-images.githubusercontent.com/8459425/60825366-73706e00-a1a3-11e9-8497-f4a39f8b3839.gif)

**Comment by sdanyliv** [comment]
Can you extend Type visualizer to replace default hint?
Name = ..., FullName=... is less readable. And it is useful just to see hint instead of invoking dialog.

**Comment by SteveWilkes** [comment]
As I understand it, the default hint is provided by `ToString()` or a `DebuggerDisplayAttribute` - it might be possible through some VS Extension wizardry, but it's not something I've done before.

**Comment by sdanyliv** [comment]
@SteveWilkes, problem still exists.
![image](https://user-images.githubusercontent.com/783759/60954467-ae8bb200-a307-11e9-923c-c4931c3df133.png)

**Comment by SteveWilkes** [comment]
Ohhhh, I see what's happened. The visualizers are at v2.4.1, but the ReadableExpressions assembly is at v2.3.2 - the installer code which updates the manifest takes its version number from the assembly.

If you look in C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\AgileObjects\ReadableExpressions.Visualizers, there'll be a v2.3.2 folder in there. The installed visualizers are the up-to-date versions, but the extension is being marked with an old version number.

I've just uploaded [v2.4.2](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers) where this should (!) be fixed.

Thanks for helping me figure this out, and please let me know how you get on :)

**Comment by gauthiermaxime** [comment]
@SteveWilkes , it's still not fixed as of v2.4.2
![2019-07-11 13_32_40-Manage Extensions](https://user-images.githubusercontent.com/26210529/61072130-a8b5cf80-a3e0-11e9-9323-c07c533df867.png)
