### ISSUE TITLE
Performance when opening and closing preview window.

### ISSUE THREAD

**Issue by sdanyliv** [agileobjects/ReadableExpressions#47]
So, i have to mention that. 
When opening preview window, it takes a seconds to open. Then after closing it - VS hangs for the same time. As result i prefer to quickly review string line instead of invoking more readable view.
Any ideas why?

**Comment by SteveWilkes** [comment]
Hi!

I have the same issue - the mouse pointer snaps back to the preview icon after closing the window, as well.

All I can say without looking into it in detail is that the translation isn't particularly slow, so the delay / hang must be Visual Studio's own infrastructure and interop code creating and disposing the window. I'll check it out and see if there's anything I can do, though.

Thanks for the feedback!

Steve

**Comment by sdanyliv** [comment]
I'm not familiar with VS extensions but as i know VS is WPF application. So mixing Winforms and WPF may cause unwanted delays.

**Comment by zspitz** [comment]
If you want to test a pure WPF visualizer, you can try my [Expression Tree Visualizer](https://github.com/zspitz/ExpressionTreeVisualizer).

But my understanding is that while running Winforms consumes less resources than WPF, which may offset the loading time for Winforms.

**Comment by SteveWilkes** [comment]
Having recently uninstalled ReSharper, the VS2019 window-opening performance has dramatically improved. Here's opening the window for a fairly large Expression tree:

![ReadableExpressions](https://user-images.githubusercontent.com/8459425/73779712-0ba7f300-4785-11ea-96c4-57c34daf1a05.gif)

...more or less instant.

Closing this issue as this seems good enough to me, and I'm not sure what I'd do about in any case! :)

Thanks for the feedback,

Steve

**Comment by sdanyliv** [comment]
Uninstall Reshaper is not a cure )) It is a workaround.
I thought you will try to create simple WPF Window to compare performance.
