### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by sdanyliv** [agileobjects/ReadableExpressions#58]
Syntax coloring is good, but...
- Font size is too big, expected same font size as in code
- Automatic window resizing is weird, better to open in the same window size and position. Maybe option for this?

**Comment by SteveWilkes** [comment]
Hello!

Thanks for the feedback - d'you mean the menu options font size?

**Comment by sdanyliv** [comment]
Two options:
- Font size
- Disable automatic resizing

**Comment by SteveWilkes** [comment]
Seems reasonable! I'll make those changes. Thanks!

**Comment by SteveWilkes** [comment]
Just to check - do you have v3 or v3.0.1 of the visualizers? Is it the menu font, code font, or both you'd like to change?

**Comment by sdanyliv** [comment]
Sorry, missed your message 3.0.1 installed.

**Comment by SteveWilkes** [comment]
Changing the code sample font family and size is supported as of v3.1, as is disabling the window resizing to match the code sample.

Thanks again for the feedback!

Steve
