### ISSUE TITLE
Moving window issue

### ISSUE THREAD

**Issue by sdanyliv** [agileobjects/ReadableExpressions#64]
Version 3.1.0

Visualize any expression, and move window up by mouse, release, move again.
You can examine preview window expanding.

**Comment by SteveWilkes** [comment]
Thanks for letting me know - I'll check it out!

**Comment by SteveWilkes** [comment]
This is fixed as of v3.2 of the Visualizers, which is now available in [the VS Marketplace](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers).

Thanks again for letting me know!
