### ISSUE TITLE
Misplaced return

### ISSUE THREAD

**Issue by lbargaoanu** [agileobjects/ReadableExpressions#7]
[This](https://gist.github.com/lbargaoanu/b8741d0c102b5b969f07d78363a8f9fd#file-map) translates to

typeMapDestination.Foos = 
{
    var passedDestination = (dest == null) ? null : typeMapDestination.Foos;
    var collectionDestination = (passedDestination != null) ? passedDestination : new List<ComplexTypeMapper.Foo>();
    return (resolvedValue == null)
        ? collectionDestination
        : {
            var enumerator = resolvedValue.GetEnumerator();
            while (true)
            {
                if (enumerator.MoveNext())
                {
                    var item = enumerator.Current;
                    collectionDestination.Add(ctxt.Map(item, null));
                }
                else
                {
                    break;
                }
            }

            return collectionDestination;
    return     }
}

**Comment by SteveWilkes** [comment]
This is fixed in the latest code - I'll release a new version around July 30th. Thanks for the bug report! :)

**Comment by lbargaoanu** [comment]
:+1:

**Comment by lbargaoanu** [comment]
The code certainly looks better, but this particular case is the same for me. Of course it's no big deal, just saying :)

**Comment by SteveWilkes** [comment]
Dammit! I'll try again :)

**Comment by lbargaoanu** [comment]
:)

**Comment by SteveWilkes** [comment]
This is fixed in 1.6.5. It really, really is :)

**Comment by lbargaoanu** [comment]
Roger :) Thanks.
