### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by lbargaoanu** [agileobjects/ReadableExpressions#78]
Extra info: https://gist.github.com/lbargaoanu/0291928f8441c2e6db339c4986fb0a9f
.Net Framework, latest VS

**Comment by schehlmj** [comment]
I am having this issue also.  I am using  
`var executionPlan = _mapper.ConfigurationProvider.BuildExecutionPlan(fromType, toType);  // AutoMapper
var executionPlanString = executionPlan.ToReadableString(c => c.UseFullyQualifiedTypeNames);` 
and getting very similar exception.

I tried with 2.5, 2.4.1, and 2.3.2.

**Comment by SteveWilkes** [comment]
Thanks for letting me know - I'll get this sorted out.

Cheers,

Steve

**Comment by SteveWilkes** [comment]
This is fixed as of [NuGet v2.5.1](https://nuget.org/packages/AgileObjects.ReadableExpressions), and [Visualizers v3.3.1](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers). 

Thanks again for letting me know!
