### ISSUE TITLE
Dont change Visual Studio language

### ISSUE THREAD

**Issue by wilsade** [agileobjects/ReadableExpressions#79]
Hi.

I use Microsoft Windows in one language and Microsoft Visual Studio in another one.
After install or update ReadableExpressions, it changes my Visual Studio language to use the "Same as Microsoft Windows".

Thanks.

**Comment by SteveWilkes** [comment]
Hi,

Thanks for the feedback, unfortunately I have no idea how this could have happened. The installer certainly doesn't explicitly change the language setting - I don't even know how (or if) it could.

I have several local Visualizer installs, and none of them have changed their VS language setting. I'm not sure how this happened, but if it was the installer, I'm not sure there'd be anything I could do about it.

All the best,

Steve

**Comment by leandromoh** [comment]
just for registre, I have this problem too @SteveWilkes
