### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by sdanyliv** [agileobjects/ReadableExpressions#88]
Well, Visual Studio 2022 preview is become usable for me. One thing that I have missed is `ReadableExpressions`.
Any plans to support?

Thanks!

**Comment by SteveWilkes** [comment]
Just to note - I use the WIX plugin to create the installer, and it's not supporting VS 2022 yet:

https://github.com/wixtoolset/issues/issues/6493

**Comment by SteveWilkes** [comment]
VS2022 is supported as of visualizers v4, which is available on [the VS marketplace](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers)! Cheers!

Here it is working on VS2022 :)
![Readable2022](https://user-images.githubusercontent.com/8459425/137266334-64723bdd-cc3b-4eca-9317-d504e54fcc26.gif)

**Comment by rizi** [comment]
> That's great - thanks for your help! I'll push the updated installer onto VS Marketplace :)

@SteveWilkes today I got an update notification from VS that a new version is available (4.1.0), I downloaded it and started the installer, the installer stated there is already a newer version installed (but I have installed you test version from above (4.0.0) --> so I decided to completely remove the installed version (with the 4.0.0 installer from above).

Than I tried to install the version 4.1.0 but it only installed the extension for VS 2019, not for VS 2022, any ideas why it's not working?

Installing 4.0.0 still works for VS 2022, so there seems to be "something wrong"/"not working correctly" in 4.1.0, can I help you to figure out whats wrong?

br

**Comment by SteveWilkes** [comment]
Oh dear... sorry to hear that - thanks for letting me know - investigating...

**Comment by SteveWilkes** [comment]
Hmm - I'm not sure what's happened, but [marketplace](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers) isn't updating the installer to the version I've uploaded. I've renamed it to put the version number on the end, and it's still downloading a file without a version number!

It may be a caching / delay - I'll check back later. In the meantime, this is the up-to-date installer, which is what market place should be downloading...

[AgileObjects.ReadableExpressions.Visualizers.4.1.0.zip](https://github.com/agileobjects/ReadableExpressions/files/7458427/AgileObjects.ReadableExpressions.Visualizers.4.1.0.zip)

**Comment by rizi** [comment]
> Hmm - I'm not sure what's happened, but [marketplace](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers) isn't updating the installer to the version I've uploaded. I've renamed it to put the version number on the end, and it's still downloading a file without a version number!
> 
> It may be a caching / delay - I'll check back later. In the meantime, this is the up-to-date installer, which is what market place should be downloading...
> 
> [AgileObjects.ReadableExpressions.Visualizers.4.1.0.zip](https://github.com/agileobjects/ReadableExpressions/files/7458427/AgileObjects.ReadableExpressions.Visualizers.4.1.0.zip)

Thank you 👍
