### ISSUE TITLE
Possible formatting bug

### ISSUE THREAD

**Issue by drlagos** [agileobjects/ReadableExpressions#9]
`v = (a, b) => (a + b)).Invoke(1, 2`

Note the missing parenthesis before the lambda and at the end of the Invoke method call.

Minimal example:

            var a = Expression.Parameter(typeof(int), "a");
            var b = Expression.Parameter(typeof(int), "b");
            var body = Expression.Block(Expression.Add(a, b));
            var lambda = Expression.Lambda(body, a, b);
            var call = Expression.Invoke(lambda, Expression.Constant(1), Expression.Constant(2));
            var variable = Expression.Variable(typeof(int), "v");
            var assign = Expression.Assign(variable, call);
            Console.WriteLine(assign.ToReadableString());

**Comment by SteveWilkes** [comment]
Good spot! Will be fixed soon :)

**Comment by drlagos** [comment]
Good to know!

**Comment by SteveWilkes** [comment]
Fixed in the latest code, release to follow :)

**Comment by SteveWilkes** [comment]
This is fixed in [release v1.9](https://github.com/agileobjects/ReadableExpressions/releases/tag/1.9.0).
