### ISSUE TITLE
Partially closed generics arrays

### ISSUE THREAD

**Issue by lbargaoanu** [agileobjects/ReadableExpressions#94]
A tricky one :)
```C#
class Switch<T>
{
	public KeyValuePair<T, int>[] Keys;
}

typeof(Switch<>).GetField("Keys").FieldType.GetFriendlyName().Dump();
```
I get "KeyValuePair`2[]".

**Comment by SteveWilkes** [comment]
Haha - yeah, ok - I'll take a look... :)

**Comment by SteveWilkes** [comment]
This change has been added to the v3.1 release, which is now [on NuGet](https://www.nuget.org/packages/AgileObjects.ReadableExpressions). Cheers!
