### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by mhsimkin** [agileobjects/ReadableExpressions#96]
Hi. I just installed version 4.1.0 of the AgileObjects Readable Expressions Visualizers.  This is my first time attempting to use the visualizers. When I attempt to open the visualizer I get the following error message: "Could not load file or assembly 'AgileObjects.ReadableExpressions, Version=3.0.1.0 ..." I have attached a screen shot.

I have AgileObjects.ReadableExpressions package version 3.0.0 published on Oct 20th, 2021 installed.

Any idea what is wrong?

Thanks

-marc
![reasableexpressions-error](https://user-images.githubusercontent.com/1248166/140566835-bfabf8ea-0ba0-4d88-a601-af46604f3d49.png)

**Comment by SteveWilkes** [comment]
Hi Marc,

Thanks for raising this! Could you let me know - were you debugging .NET Framework or .NET Core, and what version of Visual Studio this was in?

Thanks,

Steve

**Comment by mhsimkin** [comment]
Latest VS2022 with latest .Net 6. The app is blazor server using .Net 6.
