### ISSUE TITLE
LINQ translation

### ISSUE THREAD

**Issue by lbargaoanu** [agileobjects/ReadableExpressions#97]
```C#
Expression<Func<int>> expr = ()=>(from s in new[]{"1","2","3","4","5"} let n = int.Parse(s) where n > 3 group s by s into result select result.Count()).Count();
expr.ToReadableString().Dump();
```
I get
```C#
() => new[] { "1", "2", "3", "4", "5" }
    .Select(s => new { s = s, n = int.Parse(s) })
    .Where(<>h__TransparentIdentifier0 => <>h__TransparentIdentifier0.n > 3)
    .GroupBy(
        <>h__TransparentIdentifier0 => <>h__TransparentIdentifier0.s,
        <>h__TransparentIdentifier0 => <>h__TransparentIdentifier0.s)
    .Select(result => result.Count())
    .Count()
```
And that makes sense. But it would be nice to have legal C# identifiers for the lambda parameters.

**Comment by SteveWilkes** [comment]
Hi,

Thanks for pointing this out - I've updated it to use an `_` for any parameters which start with `<>`.

I've also made it translate to `new { s, n = int.Parse(s) }`, instead of `new { s = s, n = int.Parse(s) }`.

Cheers,

Steve

**Comment by lbargaoanu** [comment]
Nice :) Thanks!

**Comment by SteveWilkes** [comment]
These changes have been added to the v3.1 release, which is now [on NuGet](https://www.nuget.org/packages/AgileObjects.ReadableExpressions). Cheers!
